# Workflow name
name: Run Tests
on: push
permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  build:
    runs-on: ubuntu-latest
    # Job steps
    steps:
        - uses: actions/checkout@v2
        - name: Install modules
          run: yarn
        - name: Run tests
          run: yarn test